# Generated by Django 4.2.2 on 2023-07-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=100, unique=True)),
                ('especialidade', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=200)),
                ('data_nascimento', models.DateField(default=None, unique=True)),
                ('cpf', models.BigIntegerField(default=None, editable=False, max_length=11, unique=True)),
                ('telefone', models.CharField(default=None, max_length=14)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('tipo_sanguineo', models.CharField(default=None, max_length=3, unique=True)),
                ('cep', models.BigIntegerField(default=None, max_length=8)),
                ('endereco', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProntuarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, unique=True)),
                ('queixa', models.TextField()),
                ('exames', models.TextField()),
                ('diagnostico', models.TextField(blank=True, unique=True)),
                ('tratamento', models.TextField(blank=True, unique=True)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.medico', verbose_name='nome')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.pessoa', verbose_name='nome')),
            ],
        ),
    ]
