# Generated by Django 4.2.2 on 2023-07-05 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='Name',
        ),
        migrations.AddField(
            model_name='medico',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='blood_type',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='prontuariomedico',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prontuariomedico',
            name='id_medico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.medico'),
        ),
        migrations.AddField(
            model_name='prontuariomedico',
            name='patologia',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='prontuariomedico',
            name='pessoa_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prontuario.pessoa'),
        ),
        migrations.AddField(
            model_name='prontuariomedico',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.BigIntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
