# Generated by Django 4.2.2 on 2023-07-08 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.BigIntegerField(default=None, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='prontuariomedico',
            name='id_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prontuario.medico', verbose_name='Medico'),
        ),
        migrations.AlterField(
            model_name='prontuariomedico',
            name='id_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prontuario.pessoa', verbose_name='Paciente'),
        ),
    ]
