# Generated by Django 4.2.2 on 2023-07-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_alter_pessoa_cpf_alter_prontuariomedico_id_medico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='cep',
            new_name='CEP',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_nascimento',
            new_name='Data de Nascimento',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='endereco',
            new_name='Endereço',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='telefone',
            new_name='Telefone',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='tipo_sanguineo',
            new_name='Tipo sanguineo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Está ativo?',
            field=models.BooleanField(default=True),
        ),
    ]
