# Generated by Django 4.2.2 on 2023-07-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_remove_pessoa_name_medico_name_pessoa_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuariomedico',
            name='id_medico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prontuario.medico'),
        ),
    ]
