# Generated by Django 4.2.2 on 2023-07-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0003_rename_cep_pessoa_cep_rename_cpf_pessoa_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='Esta ativo?',
            field=models.BooleanField(default=True),
        ),
    ]
