# Generated by Django 4.2.2 on 2023-07-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0003_alter_prontuariomedico_id_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuariomedico',
            name='id_medico',
        ),
    ]
