# Generated by Django 4.2.2 on 2023-07-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0004_medico_esta_ativo_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prontuariomedico',
            old_name='id_medico',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='prontuariomedico',
            old_name='id_pessoa',
            new_name='pessoa',
        ),
    ]
